services:
  webapi:
    container_name: webapi_container
    ports:
      - "5000:5000"
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=sara;Password=mysecretpassword;Server=postgres_container;Port=5432;Database=SampleDB;IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - dev_network
  postgres_db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: sara
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /data/postgres
    volumes:
       - postgres_data:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - dev_network
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin

    ports:
      - "8080:80"
    networks:
      - dev_network
    restart: unless-stopped
    
networks:
  dev_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: